/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RouterPath
 * Author: Victor
 * Date: 2023/3/3 11:55
 * Description: 
 * -----------------------------------------------------------------
 */
export default class RouterPath {
  static readonly INDEX_PAGE = 'pages/Index';
  static readonly SPLASH_PAGE = 'pages/SplashPage';
  static readonly WEB_PAGE = 'pages/common/WebPage';
  static readonly MAIN_PAGE = 'pages/MainPage';
  static readonly SEARCH_PAGE = 'pages/home/SearchPage';
  static readonly SEARCH_RESULT_PAGE = 'pages/home/SearchResultPage';
  static readonly VIDEO_DETAIL_PAGE = 'pages/VideoDetailPage';
  static readonly POSTER_PAGE = 'pages/common/PosterPage';
  static readonly LIGHT_TOPICS_PAGE = 'pages/LightTopicsPage';
  static readonly USER_PAGE = 'pages/UserPage';
  static readonly CODE_LOGIN_PAGE = 'pages/login/CodeLoginPage';
  static readonly HOME_RECOMMEND_MORE_PAGE = 'pages/home/HomeRecommendMorePage';
  static readonly YOU_MAY_LIKE_MORE_PAGE = 'pages/home/YouMayLikeMorePage';
  static readonly SPIKE_ZONE_MORE_PAGE = 'pages/SpikeZoneMorePage';
  static readonly PURCHASED_COURSE_PAGE = 'pages/home/PurchasedCoursePage';
  static readonly COURSE_CATEGORY_PAGE = 'pages/course/CourseCategoryPage';
  static readonly COURSE_COMMENT_SUBMIT_PAGE = 'pages/course/CourseCommentSubmitPage';
  static readonly MY_PRACTICE_PAGE = 'pages/studycenter/MyPracticePage';
  static readonly STUDY_MATERIAL_PAGE = 'pages/studycenter/StudyMaterialPage';
  static readonly STUDY_MATERIAL_MORE_PAGE = 'pages/studycenter/StudyMaterialMorePage';
  static readonly WATCH_HISTORY_PAGE = 'pages/studycenter/WatchHistoryPage';
  static readonly MY_COUPON_PAGE = 'pages/me/MyCouponPage';
  static readonly MY_FAVORITE_PAGE = 'pages/me/MyFavoritePage';
  static readonly SETTING_PAGE = 'pages/me/SettingPage';
  static readonly SERVICE_CENTER_PAGE = 'pages/ServiceCenterPage';
  static readonly FEEDBACK_PAGE = 'pages/me/FeedbackPage';
  static readonly FEEDBACK_SUCCESS_PAGE = 'pages/me/FeedbackSuccessPage';
  static readonly ACCOUNT_SETTING_PAGE = 'pages/me/AccountSettingPage';
  static readonly PRIVACY_SETTING_PAGE = 'pages/me/PrivacySettingPage';
  static readonly PUSH_SETTING_PAGE = 'pages/me/PushSettingPage';
  static readonly ABOUT_US_PAGE = 'pages/me/AboutUsPage';
  static readonly MODIFY_BIND_PHONE_PAGE = 'pages/me/ModifyBindPhonePage';
  static readonly SMS_VERIFICATION_PAGE = 'pages/me/SmsVerificationPage';
  static readonly ENTER_NEW_PHONE_PAGE = 'pages/me/EnterNewPhonePage';
  static readonly CONFIRM_PHONE_PAGE = 'pages/me/ConfirmPhonePage';
  static readonly MODIFY_BIND_PHONE_SUCCESS_PAGE = 'pages/me/ModifyBindPhoneSuccessPage';
  static readonly MODIFY_BIND_PHONE_EXIST_PAGE = 'pages/me/ModifyBindPhoneExistPage';
  static readonly MODIFY_BIND_PHONE_FAILED_PAGE = 'pages/me/ModifyBindPhoneFailedPage';
  static readonly CANCEL_ACCOUNT_PAGE = 'pages/me/CancelAccountPage';
  static readonly ACCOUNT_CANCEL_VERIFICATION_PAGE = 'pages/me/AccountCancelVerificationPage';
  static readonly EDIT_PROFILE_PAGE = 'pages/me/EditProfilePage';
  static readonly LOGISTICS_PAGE = 'pages/me/LogisticsPage';
  static readonly INVOICE_SERVICE_PAGE = 'pages/me/InvoiceServicePage';
  static readonly NOT_INVOICED_PAGE = 'pages/me/NotInvoicedPage';
  static readonly INVOICE_DETAIL_PAGE = 'pages/me/InvoiceDetailPage';
  static readonly INVOICE_PAGE = 'pages/me/InvoicePage';
  static readonly VIEW_INVOICE_PAGE = 'pages/me/ViewInvoicePage';
  static readonly MY_ORDER_PAGE = 'pages/order/MyOrderPage';
  static readonly AFTER_SALE_PAGE = 'pages/order/AfterSalePage';
  static readonly REFUND_PAGE = 'pages/order/RefundPage';
  static readonly AFTER_SALE_ORDER_CLOSE_PAGE = 'pages/order/AfterSaleOrderClosePage';
  static readonly NOTIFICATION_PAGE = 'pages/message/NotificationPage';
  static readonly ORDER_DETAIL_PAGE = 'pages/order/OrderDetailPage';
  static readonly ONLY_REFUND_PAGE = 'pages/order/OnlyRefundPage';
  static readonly MODIFY_ONLY_REFUND_PAGE = 'pages/order/ModifyOnlyRefundPage';
  static readonly AFTER_SALE_RECORD_PAGE = 'pages/order/AfterSaleRecordPage';
  static readonly ONLINE_COURSE_DETAIL_PAGE = 'pages/course/OnlineCourseDetailPage';
  static readonly OFFLINE_COURSE_DETAIL_PAGE = 'pages/course/OfflineCourseDetailPage';
  static readonly COURSE_COMMENT_PAGE = 'pages/course/CourseCommentPage';
  static readonly TEACHER_DETAIL_PAGE = 'pages/home/TeacherDetailPage';
  static readonly ONLINE_COURSE_STUDY_PLAY_PAGE = 'pages/course/OnlineCourseStudyPlayPage';
  static readonly ORGAN_MAIN_PAGE = 'pages/home/OrganMainPage';
  static readonly HOT_LIVE_MORE_PAGE = 'pages/home/HotLiveMorePage';
  static readonly TRY_PLAY_PAGE = 'pages/course/CourseTryPlayPage';
  static readonly PAY_ORDER_PAGE = 'pages/pay/PayOrderPage';
  static readonly PAY_SUCCESS_PAGE = 'pages/pay/PaySuccessPage';
  static readonly PAY_FAILED_PAGE = 'pages/pay/PayFailedPage';
  static readonly COURSE_PRACTICE_PAGE = 'pages/studycenter/CoursePracticePage';
  static readonly OFFLINE_COURSE_STUDY_PLAY_PAGE = 'pages/course/OfflineCourseStudyPlayPage';
  static readonly OFFLINE_COURSE_STUDY_UN_PLAY_PAGE = 'pages/course/OfflineCourseStudyUnPlayPage';
}