/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CollectApi
 * Author: Victor
 * Date: 2023/11/20 18:48
 * Description: 
 * -----------------------------------------------------------------
 */
export class CollectApi {
  static readonly COLLECT = 'cloud/user/pf/user-collection/collect'
  static readonly COLLECTION_PAGE = 'cloud/user/pf/user-collection/page/v2'
}