/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CommentApi
 * Author: Victor
 * Date: 2023/12/29 10:11
 * Description: 
 * -----------------------------------------------------------------
 */
export class CommentApi {
  static readonly COMMENT_NUM = 'cloud/user/evaluate/open/recommend/num'
  static readonly COMMENT_LIST = 'cloud/user/evaluate/get'
  static readonly RECOMMEND_COMMENT = 'cloud/user/evaluate/open/recommend/evaluate'
  static readonly EVALUATE_LECTURER = 'cloud/user/evaluate/get/lecturer'
  static readonly EVALUATE_CHECK = 'cloud/user/evaluate/check'
  static readonly ADD_COMMENT = 'cloud/user/evaluate/add'
  static readonly EDIT_COMMENT = 'cloud/user/evaluate/edit'
  static readonly COMMENT_DETAIL = 'cloud/user/evaluate/detail'
}