/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: HtmlApi
 * Author: Victor
 * Date: 2023/12/04 20:14
 * Description: 
 * -----------------------------------------------------------------
 */
export class HtmlApi {
  static readonly ABOUS_HOK: string = 'http://static.about.us.hokkj.cn/';//关于我们
  static readonly USER_SERVICES_AGREEMENT: string = 'http://static.user.service.hokkj.cn/';
  static readonly PRIVACY_POLICY: string = 'http://static.privacy.hokkj.cn/';
  static readonly WATCH_SOLUTION_URL = 'https://ap.hokkj.cn/guidePage/android'
  static readonly PDF_JS = 'https://mozilla.github.io/pdf.js/web/viewer.html?file='
}