/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: MessageApi
 * Author: Victor
 * Date: 2023/12/21 15:01
 * Description: 
 * -----------------------------------------------------------------
 */
export class MessageApi {
  static readonly GET_NOTIFICATION = 'cloud/msg/internal-msg/pf/page'
  static readonly READ_NOTIFICATIONS = 'cloud/msg/internal-msg/signList'
  static readonly SIGN_STATUS = 'cloud/msg/internal-msg/signStatus/type/user'
  static readonly FEED_BACK_CODE = "cloud/user/pf/message/send/code"
  static readonly FEED_BACK = 'cloud/user/pf/message/save'
}