/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: OrganHomeApi
 * Author: Victor
 * Date: 2024/04/15 15:15
 * Description: 
 * -----------------------------------------------------------------
 */
export class OrganHomeApi {
  static readonly TENANT_HOME = 'cloud/user/tenant/home'
  static readonly HOT_LIVE = 'cloud/edata-live/user/open/hot/live'
  static readonly TENANT_AD = 'cloud/user/ad-do/list'

}