/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SearchApi
 * Author: Victor
 * Date: 2023/11/29 12:23
 * Description: 
 * -----------------------------------------------------------------
 */
export class SearchApi {
  static readonly SEARCH_TREND = 'cloud/user/pf/search/trend'
  static readonly SEARCH_COURSE_PAGE = 'cloud/user/pf/search/keywordGoodsInfo'
  static readonly SEARCH_TEACHER_PAGE = 'cloud/user/pf/search/keywordLecturer'
  static readonly SEARCH_TENANT_PAGE = 'cloud/user/pf/search/keywordTenant'
}