/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ShoppingCartApi
 * Author: Victor
 * Date: 2023/11/20 18:48
 * Description: 
 * -----------------------------------------------------------------
 */
export class ShoppingCartApi {
  static readonly SHOPPING_CART = 'cloud/user/cart/user/v3'
  static readonly SET_CART = 'cloud/user/cart/setCart'
  static readonly REMOVE_CART = 'cloud/user/cart/remove/list'
  static readonly CLEAR_CART = 'cloud/user/cart/remove'
  static readonly CART_TOTAL = 'cloud/user/cart/total'
  static readonly GOODS_SPEC = "cloud/user/cart/goods/"
}