/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: TeacherApi
 * Author: Victor
 * Date: 2024/02/01 18:28
 * Description: 
 * -----------------------------------------------------------------
 */
export class TeacherApi {
  static readonly TEACHER_DETAIL = 'cloud/user/lecturer/detail'
  static readonly TEACHER_ONLINE = 'cloud/user/home/goods/lecturer/online/list'
  static readonly TEACHER_OFFLINE = 'cloud/user/home/goods/lecturer/offline/list'
  static readonly TEACHER_LIST = 'cloud/user/lecturer/page'
  static readonly TEACHER_SHARE_INFO = 'cloud/user/lecturer/Lecturer/share'
}