/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: UploadApi
 * Author: Victor
 * Date: 2023/12/05 19:16
 * Description: 
 * -----------------------------------------------------------------
 */
export class UploadApi {
 static readonly UPLOAD_IMG = 'cloud/user/upload/img'
 static readonly UPLOAD_IMG_MULTI = 'cloud/user/upload/img/multi'
}