/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: UserApi
 * Author: Victor
 * Date: 2023/11/27 14:05
 * Description: 
 * -----------------------------------------------------------------
 */
export class UserApi {
  static readonly USER_INFO = 'cloud/edata-customer/user/pf/user/current/info'
  static readonly COUPON_PAGE = 'cloud/user/coupon/my/page'
  static readonly SERVICE_INFO = 'cloud/user/service/info'
  static readonly CHECK_VERSION = 'cloud/user/app/version/check'
}