/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: PlayPageInfo
 * Author: Victor
 * Date: 2024/05/21 15:45
 * Description: 
 * -----------------------------------------------------------------
 */

export class PlayPageInfo {
 static readonly PLAY_SPEED: 1
 static readonly VOLUME: 0.5
 static readonly VOLUME_SHOW: false
 static readonly BRIGHT: 0.5
 static readonly BRIGHT_SHOW: false
 static readonly POSITION_X: 0
 static readonly POSITION_Y: 0
 static readonly HEIGHT: '7.2%'
 static readonly PLAY_PLAYER_HEIGHT: '25.6%'
 static readonly PLAY_PLAYER_HEIGHT_FULL: '75.4%'
 static readonly PLAY_PROGRESS_HEIGHT: '7.1%'
 static readonly COLUMN_HEIGHT_ONE: '26.9%'
 static readonly COLUMN_HEIGHT_TWO: '22.9%'
 static readonly MIN_ANGLE: 0
 static readonly MAX_ANGLE: 30
 static readonly MIN_VALUE: 0
 static readonly MAX_VALUE: 1
 static readonly DISAPPEAR_TIME: 200
 static readonly MARGIN_ZERO: '0'
}