/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: PlayerThis
 * Author: Victor
 * Date: 2024/05/21 15:39
 * Description: 
 * -----------------------------------------------------------------
 */

export class PlayerThis {
  showBuyPlay?: boolean
  showLoading?: boolean
}