/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: PlayPageThis
 * Author: Victor
 * Date: 2024/05/21 15:43
 * Description: 
 * -----------------------------------------------------------------
 */

export class PlayPageThis {
  videoWidth?: string
  videoHeight?: string
  videoPosition?: number
  videoMargin?: string
}