/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: PlayPlayerInfo
 * Author: Victor
 * Date: 2024/05/21 15:53
 * Description: 
 * -----------------------------------------------------------------
 */

export class PlayPlayerInfo {
  static readonly ID: ''
  static readonly TYPE: 'surface'
  static readonly LIBRARY_NAME: ''
  static readonly SURFACE_WIDTH: 1920
  static readonly SURFACE_HEIGHT: 1080
  static readonly STACK_WIDTH: '16.7%'
  static readonly IMAGE_WIDTH: '95%'
  static readonly FIRST: 0
  static readonly NEXT: 1
  static readonly DURATION: 0
}