/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ContentType
 * Author: Victor
 * Date: 2023/12/05 10:22
 * Description: 
 * -----------------------------------------------------------------
 */
export const enum ContentType {
  JSON = 'application/json',
  FORM = 'multipart/form-data'
}