/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: UploadResponse
 * Author: Victor
 * Date: 2024/07/05 09:21
 * Description: 
 * -----------------------------------------------------------------
 */

export class UploadResponse {
  body?: string
}