/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: UploadUrlInfo
 * Author: Victor
 * Date: 2024/07/05 09:58
 * Description: 
 * -----------------------------------------------------------------
 */

export class UploadUrlInfo {
 url?: string
 urls?: Array<string>
}