/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: AddGoodOrderInfo
 * Author: Victor
 * Date: 2024/03/29 18:32
 * Description: 
 * -----------------------------------------------------------------
 */
export class AddGoodOrderInfo {
  goodsId?: string//商品id
  goodsNum?: number//商品数量
  specId?: string//商品规格id 线下商品必传
}