/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: AddGoodOrderParm
 * Author: Victor
 * Date: 2024/03/29 18:31
 * Description: 
 * -----------------------------------------------------------------
 */
import { AddGoodOrderInfo } from './AddGoodOrderInfo'
export class AddGoodOrderParm {
  goodsOrders?: Array<AddGoodOrderInfo>
  userCouponNoList?: Array<String>
}