/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: AnswerListData
 * Author: Victor
 * Date: 2024/06/28 16:39
 * Description: 
 * -----------------------------------------------------------------
 */
import { AnswerInfo } from './AnswerInfo'

export class AnswerListData {
  practiceId?: number
  records?: Array<AnswerInfo>
}