/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: AnswerParm
 * Author: Victor
 * Date: 2024/04/01 15:15
 * Description: 
 * -----------------------------------------------------------------
 */
export class AnswerParm {
  answer?: string
  practiceId?: number
}