/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: AutoClaimCouponParm
 * Author: Victor
 * Date: 2024/07/10 18:24
 * Description: 
 * -----------------------------------------------------------------
 */

export class AutoClaimCouponParm {
  goodsId?: string//优惠券编码
  tenantId?: number//租户ID
}