/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ClaimCouponParm
 * Author: Victor
 * Date: 2024/07/10 18:23
 * Description: 
 * -----------------------------------------------------------------
 */

export class ClaimCouponParm {
  couponNo?: string//优惠券编码
}