/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CodeLoginParm
 * Author: Victor
 * Date: 2023/11/20 18:58
 * Description: 
 * -----------------------------------------------------------------
 */
export class CodeLoginParm {
  phone?: string
  code?: string
}