/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CollectParm
 * Author: Victor
 * Date: 2023/12/04 19:53
 * Description:
 * -----------------------------------------------------------------
 */
export class CollectParm {
  collectFlag?: boolean //是否收藏
  goodsId?: string //商品编号
}