/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CommentNumData
 * Author: Victor
 * Date: 2023/12/27 11?:55
 * Description:
 * -----------------------------------------------------------------
 */
export class CommentNumData {
  evaluateNum?: number//总评论数
  goodEvaluateNum?: number//好评评论数
  medEvaluateNum?: number//中评评论数
  negEvaluateNum?: number//差评评论数
}