/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CourseEvaluateCheckData
 * Author: Victor
 * Date: 2024/07/05 10:11
 * Description: 
 * -----------------------------------------------------------------
 */

export class CourseEvaluateCheckData {
  has?: boolean
  markContent?: string
}