/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CoursePractisePageParm
 * Author: Victor
 * Date: 2024/04/01 18:50
 * Description: 
 * -----------------------------------------------------------------
 */
export class CoursePractisePageParm {
  current?: number
  practiceId?: number
}