/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CourseTenantInfo
 * Author: Victor
 * Date: 2024/04/03 11:01
 * Description: 
 * -----------------------------------------------------------------
 */
export class CourseTenantInfo {
  logoUrl?: string
  tenantName?: string
  tenantId?: number
}