/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CourseAssureInfo
 * Author: Victor
 * Date: 2023/12/28 16:33
 * Description:
 * -----------------------------------------------------------------
 */
export class CourseAssureInfo {
  assureIconResId?: Resource
  assureTitle?: string
  assureContent?: string
}