/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: CoverUrlExtendInfo
 * Author: Victor
 * Date: 2023/11/17 18:40
 * Description: 
 * -----------------------------------------------------------------
 */
export class CoverUrlExtendInfo {
  big?: string
  centre?: string
  coverUrl?: string
  goodsId?: string
  small?: string
}