/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: InvoiceCompanyInfo
 * Author: Victor
 * Date: 2024/07/11 15:54
 * Description: 
 * -----------------------------------------------------------------
 */

export class InvoiceCompanyInfo {
  creditNo?: string//公司税号
  name?: string//公司名称
}