/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: LecturerInfo
 * Author: Victor
 * Date: 2023/11/17 18:27
 * Description: 
 * -----------------------------------------------------------------
 */
export class LecturerInfo {
   lecturerId?: string//讲师id
   lecturerLabel?: string//讲师标签
   lecturerName?: string//讲师名称
   coverUrl?: string//讲师海报
   headUrl?: string//讲师海报
}