/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: LogisticsInfo
 * Author: Victor
 * Date: 2024/07/03 17:49
 * Description: 
 * -----------------------------------------------------------------
 */
import { SubLogisticsInfo } from './SubLogisticsInfo'

export class LogisticsInfo {
  dataList?: Array<SubLogisticsInfo>
  expressCode?: string
  logisticName?: string
}