/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: LogisticsData
 * Author: Victor
 * Date: 2024/07/03 17:49
 * Description: 
 * -----------------------------------------------------------------
 */
import { LogisticsInfo } from './LogisticsInfo'

export class LogisticsData {
  dataList?: Array<LogisticsInfo>
}