/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: LoginParm
 * Author: Victor
 * Date: 2023/12/08 16:51
 * Description: 
 * -----------------------------------------------------------------
 */
import { BaseParm } from './BaseParm';

export class LoginParm extends BaseParm {
 
}