/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: MaterialInfo
 * Author: Victor
 * Date: 2023/12/01 17:06
 * Description:
 * -----------------------------------------------------------------
 */
export class MaterialInfo {
  goodsId?: string
  id?: string
  materialDes?: string
  materialFrameUrl?: string
  materialId?: string
  materialName?: string
  materialUrl?: string
  remark?: string
  materialSize?: number
  materialType?: number
}