/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: MaterialData
 * Author: Victor
 * Date: 2024/04/01 17:07
 * Description: 
 * -----------------------------------------------------------------
 */
import { MaterialInfo } from './MaterialInfo'
export class MaterialData {
  contentName?: string
  goodsId?: string
  lecturerLabel?: string
  lecturerName?: string
  materialInfoVoList?: Array<MaterialInfo>
}