/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ModifyPhoneParm
 * Author: Victor
 * Date: 2023/12/07 15:35
 * Description: 
 * -----------------------------------------------------------------
 */
export class ModifyPhoneParm {
  newPhone?: string //新手机号
  oldPhone?: string //旧手机号
}