/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ModifyPhoneCodeCheckParm
 * Author: Victor
 * Date: 2023/12/07 14:46
 * Description: 
 * -----------------------------------------------------------------
 */
export class ModifyPhoneCodeCheckParm {
  code?: string //手机号验证码
  phone?: string //手机号
}