/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: NotificationParm
 * Author: Victor
 * Date: 2023/12/21 15:04
 * Description: 
 * -----------------------------------------------------------------
 */
export class NotificationParm {
  current?: number
  size?: number
  msgType?: number//1,通知2,交易;3,优惠
}