/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: OfflineVideoInfo
 * Author: Victor
 * Date: 2023/11/17 18:37
 * Description:
 * -----------------------------------------------------------------
 */
export class OfflineVideoInfo {
  duration?: number//
  goodsId?:string//
  name?:string//
  url?:string//
  materialId?:string//
  goodsType?: number//服务器暂无此字段
}