/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: OrderRecommendInfo
 * Author: Victor
 * Date: 2024/07/08 18:14
 * Description: 
 * -----------------------------------------------------------------
 */

export class OrderRecommendInfo {
  goodsId?: string
  goodsName?: string
  headUrl?: string
  lecturerLabel?: string
  goodsMode?: number
  goodsPopularity?: number
  goodsScore?: number
  tenantId?: number
}