/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: OrderGoodRelatedData
 * Author: Victor
 * Date: 2024/07/08 17:06
 * Description: 
 * -----------------------------------------------------------------
 */

export class OrderGoodRelatedData {
  goodsNum?: number//商品库存数量
  outOfTime?: boolean//订单是否过期
  shelveFlag?: number//上架状态
}