/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: PlayEvents
 * Author: Victor
 * Date: 2024/03/15 16:50
 * Description: 
 * -----------------------------------------------------------------
 */
export enum PlayEvents {
  STATE_CHANGE = 'stateChange',
  TIME_UPDATE = 'timeUpdate',
  ERROR = 'error'
}