/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: PopularityGroupInfo
 * Author: Victor
 * Date: 2023/11/16 20:02
 * Description: 
 * -----------------------------------------------------------------
 */
export class PopularityGroupInfo {
  groupingId?: string//分组id
  groupingName?: string//分组名称
}