/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RecommendCouponParm
 * Author: Victor
 * Date: 2024/07/10 17:40
 * Description: 
 * -----------------------------------------------------------------
 */
import { RecommendCouponBean } from './RecommendCouponBean'

export class RecommendCouponParm {
  orderNo?: string
  reqList?: Array<RecommendCouponBean>
}