/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RecommendCouponBean
 * Author: Victor
 * Date: 2024/07/10 17:40
 * Description: 
 * -----------------------------------------------------------------
 */

export class RecommendCouponBean {
  goodsId?: string
  specId?: string
  salePrice?: number
}