/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RemoveCartGoodsInfo
 * Author: Victor
 * Date: 2023/11/28 15:40
 * Description: 
 * -----------------------------------------------------------------
 */
export class RemoveCartGoodsInfo {
  goodsId?: string//商品编号
  specId?: string//规格编号
}