/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SearchTeacherPageParm
 * Author: Victor
 * Date: 2023/11/30 11:16
 * Description: 
 * -----------------------------------------------------------------
 */
export class SearchTeacherPageParm {
  keyword?: string//讲师名称
  current?: number//当前页
  size?: number//每页显示条数，默认 10
}