/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SearchTendInfo
 * Author: Victor
 * Date: 2023/11/16 17:00
 * Description: 
 * -----------------------------------------------------------------
 */
export class SearchTrendInfo {
  searchId?: string//搜索id
  searchValue?: string//搜索关键词
}