/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SearchTenantInfo
 * Author: Victor
 * Date: 2024/04/03 11:14
 * Description: 
 * -----------------------------------------------------------------
 */
export class SearchTenantInfo {
  abbreviation?: string//机构英文缩写
  bigLogo?: string//机构Logo地址大
  companyAbbreviation?: string//机构简介
  name?: string//组织名称
  smallLogo?: string//机构Logo地址小
  douAuth?: boolean
  organizationId?: number//组织id
}