/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SearchCourseParm
 * Author: Victor
 * Date: 2023/11/30 11:35
 * Description: 
 * -----------------------------------------------------------------
 */
export class SearchCourseParm {
  current?: number//当前页
  size?: number//每页显示条数，默认 10
  keyword?: string//搜索关键字
}