/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SendInvoiceParm
 * Author: Victor
 * Date: 2024/07/11 15:59
 * Description: 
 * -----------------------------------------------------------------
 */

export class SendInvoiceParm {
  invoiceId?: string//发票id
  orderNo?: string//订单号
  receivingEmail?: string//接收邮箱
}