/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: ServiceInfo
 * Author: Victor
 * Date: 2023/12/05 15:55
 * Description: 
 * -----------------------------------------------------------------
 */
export class ServiceInfo {
  remark?: string //说明
  phone?: string //客服电话
}