/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SetCartParm
 * Author: Victor
 * Date: 2023/11/27 19:33
 * Description: 
 * -----------------------------------------------------------------
 */
export class SetCartParm {
  goodsId?: string//商品编号
  quantity?: number//商品数量
  specId?: string//商品规格id
}