/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SignStatusInfo
 * Author: Victor
 * Date: 2023/12/21 18:24
 * Description: 
 * -----------------------------------------------------------------
 */
export class SignStatusInfo {
  msgType?: number
  signStatus?: number //1未签收 2已签收
}