/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SubLogisticsInfo
 * Author: Victor
 * Date: 2024/07/03 17:51
 * Description: 
 * -----------------------------------------------------------------
 */

export class SubLogisticsInfo {
  acceptStation?: string = '阿打发打发是的噶第三方双缝干涉电饭锅森岛帆高是大法官森岛帆高森岛帆高森岛帆高森岛帆高'
  acceptTime?: string = '2024-07-03 20:09'
}