/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: SummaryStudyData
 * Author: Victor
 * Date: 2023/11/22 19:16
 * Description: 
 * -----------------------------------------------------------------
 */
export class SummaryStudyData {
  todayAccumulated?: number//今日播放时长
  totalAccumulated?: number//累计播放时长
}