/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: TeacherDetailData
 * Author: Victor
 * Date: 2024/02/01 11?:29
 * Description:
 * -----------------------------------------------------------------
 */
export class TeacherDetailData {
  backgroundUrl?: string//背景图存储路径
  briefIntroduction?: string//说明
  content?: string//详情
  headUrl?: string//讲师头像
  coverUrl?: string//封面存储路径
  lecturerId?: string//讲师id
  lecturerLabel?: string//标签
  lecturerName?: string//讲师名称
}