/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: TenantInfo
 * Author: Victor
 * Date: 2024/04/02 14:15
 * Description: 
 * -----------------------------------------------------------------
 */
export class TenantInfo {
  douAuth?: boolean//抖音小程序权限
  logoUrl?: string//机构Logo地址
  tenantDesc?: string//机构简介
  tenantName?: string//机构名称
  tenantId?: number//机构ID
}