/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: WatchHistoryParm
 * Author: Victor
 * Date: 2023/11/22 17:01
 * Description: 
 * -----------------------------------------------------------------
 */
export class WatchHistoryParm {
  current?: number//当前页
  size?: number//每页显示条数，默认 10
}