export class PlayConstants {
  static readonly PLAY_INDEX = 'PLAY_INDEX' // 当前播放位置
  static readonly PLAY_LAST_PROGRESS_INFO = 'PLAY_LAST_PROGRESS_INFO' // 上一次播放信息
  static readonly PLAY_LAST_POSITION = 'PLAY_LAST_POSITION' // 上一次播放时间，单位秒
  static readonly PLAY_LAST_INDEX = 'PLAY_LAST_INDEX' // 上一次播放位置
  static readonly PLAY_IS_FULL_SCREEN = 'PLAY_IS_FULL_SCREEN' // 是否全屏播放
  static readonly PLAY_URL = 'PLAY_URL' // 当前播放地址
  static readonly PLAY_TITLE = 'PLAY_TITLE' // 当前播放视频标题
  static readonly PLAY_IS_SHOW_BUY = 'PLAY_IS_SHOW_BUY' // 是否展示购买按钮
  static readonly PLAY_MANAGE = 'PLAY_MANAGE' // 播放器管理类
  static readonly PLAY_STATE = 'PLAY_STATE' // 当前播放状态
  static readonly PLAY_IS_TRY_END = 'PLAY_IS_TRY_END' // 试看结束
}